try {
    throw 'An error'
} catch {
    Write-Host 'Caught an error'
}
